### PR TITLE
Repositioned torches

### PR DESCRIPTION
**Pull request by AdamPlenty**
Fixes dkfans/keeperfx#3290

See also dkfans/keeperfx#3305

### CODE REVIEW

**Comment by AdamPlenty** [comment]
Not sure if this properly fixes possession, though 🤔.

**Comment by Loobinex** [comment]
> Not sure if this properly fixes possession, though 🤔.

Why didn't you try it?

**Comment by AdamPlenty** [comment]
> > Not sure if this properly fixes possession, though 🤔.
> 
> Why didn't you try it?

I did. There still seems to be a gap between the right torch and the wall:

image

**Comment by Loobinex** [comment]
> I did. There still seems to be a gap between the right torch and the wall:

yeah,... I pushed an improvement. Agreed? You'd need to update the flameoffset pr to match.

**Comment by AdamPlenty** [comment]
> > I did. There still seems to be a gap between the right torch and the wall:
> 
> yeah,... I pushed an improvement. Agreed? You'd need to update the flameoffset pr to match.

There still seems to be a bigger gap on the right hand-side than the left hand-side.

**Comment by Loobinex** [comment]
> There still seems to be a bigger gap on the right hand-side than the left hand-side.

then push it over some more?

**Comment by AdamPlenty** [comment]
> > There still seems to be a bigger gap on the right hand-side than the left hand-side.
> 
> then push it over some more?

If anything, there's now a slightly bigger gap on the left hand-side, but I suppose it's impossible for it to be exactly even, due to the odd number of pixels for the width?

**Comment by Loobinex** [comment]
It's not possible to move half-pixels no.

**Comment by Loobinex** [comment]
> If anything, there's now a slightly bigger gap on the left hand-side, but I suppose it's impossible for it to be exactly even, due to the odd number of pixels for the width?

But you moved it one pixel over,... is it now less wrong on the left side than it was on the right side before your latest commit? If they are equally wrong, I suggest we chose the 'wrong' side that is closest to the original experience.

**Comment by AdamPlenty** [comment]
Looking at it again, I don't think the difference is very noticeable:

image

**Pull request merged**
